#!/usr/bin/env bash

## Initialize a Docksal powered Drupal 7 site
##
## Usage: fin init

# Abort if anything fails
set -e

#-------------------------- Settings --------------------------------

# PROJECT_ROOT is passed from fin.
# The following variables are configured in the '.env' file: DOCROOT, VIRTUAL_HOST.

SITE_DIRECTORY="default"
DOCROOT_PATH="${PROJECT_ROOT}/${DOCROOT}"
SITEDIR_PATH="${DOCROOT_PATH}/sites/${SITE_DIRECTORY}"

#( set -o posix ; set ) 

#-------------------------- END: Settings --------------------------------

#-------------------------- Helper functions --------------------------------

# Console colors
red='\033[0;31m'
green='\033[0;32m'
green_bg='\033[42m'
yellow='\033[1;33m'
NC='\033[0m'

echo-red () { echo -e "${red}$1${NC}"; }
echo-green () { echo -e "${green}$1${NC}"; }
echo-green-bg () { echo -e "${green_bg}$1${NC}"; }
echo-yellow () { echo -e "${yellow}$1${NC}"; }

is_windows ()
{
	local res=$(uname | grep 'CYGWIN_NT')
	if [[ "$res" != "" ]]; then
		return 0
	else
		return 1
	fi
}

#-------------------------- END: Helper functions --------------------------------

#-------------------------- Functions --------------------------------

# Import database dump
import_database ()
{
	gzcat ${PROJECT_ROOT}/../lb.gz | fin db import --progress
}

cleanup_tables() {
  fin db import --no-truncate < ${PROJECT_ROOT}/.docksal/commands/dbimage-data/cleanup.sql
}

optimize_tables() {
  fin exec "mysqlcheck -os -hdb -uuser -puser default"
}

export_data_volume() {
  DB_CONTAINER=`fin docker-compose ps -q db`
 
  echo "Stopping db service container..."
  fin docker stop $DB_CONTAINER
  
  echo "Exporting db data volume..."
  fin docker run --rm --volumes-from $DB_CONTAINER carinamarina/backup backup \
    --source /var/lib/mysql/ --stdout --zip > ${DB_DATA_VOLUME}
}

upload_data_volume() {
  echo "DB DATA VOLUME uploading is not implemented yet"
  #scp ${PROJECT_ROOT}/dumps/ygbw-db-data-volume.tar.gz fivejars.ci:/home/jslave/dumps/ygbw-db-data-volume.tar.gz
  #scp ${PROJECT_ROOT}/dumps/ygbw-db-data-volume-small.tar.gz fivejars.ci:/home/jslave/dumps/ygbw-db-data-volume-small.tar.gz
}

#-------------------------- END: Functions --------------------------------

#-------------------------- Execution --------------------------------

if [[ "$PROJECT_ROOT" == "" ]]; then
	echo-red "\$PROJECT_ROOT is not set"
	exit 1
fi

if [[ $DOCKER_RUNNING == "true" ]]; then
	echo -e "${green_bg} Step 1 ${NC}${green} Recreating services...${NC}"
	fin reset -f
else
	echo -e "${green_bg} Step 1 ${NC}${green} Creating services...${NC}"
	fin up
fi

echo "Waiting 10s for MySQL to initialize...";
sleep 10

echo -e "${green_bg} Step 2 ${NC}${green} Importing the database dump...${NC}"
time import_database

echo -e "${green_bg} Step 3 ${NC}${green} Cleaning the database up...${NC}"
time cleanup_tables

echo -e "${green_bg} Step 4 ${NC}${green} Optimizing database tables...${NC}"
time optimize_tables

echo -e "${green_bg} Step 5 ${NC}${green} Exporting the database data volume...${NC}"
time export_data_volume

echo -e "${green_bg} Step 6 ${NC}${green} Uploading the volume...${NC}"
time upload_data_volume

#-------------------------- END: Execution --------------------------------
