#!/usr/bin/env bash

## Test site installation
##
## Usage: fin test

# Abort if anything fails
set -e

# Debug mode switch
if [[ "${DEBUG}" != "" ]]; then
    set -x
fi

echo "Testing home page..."
curl -sL -I http://${SHIELD_USER}:${SHIELD_PASS}@${VIRTUAL_HOST} | grep "HTTP/1.1 200 OK"
curl -sL http://${SHIELD_USER}:${SHIELD_PASS}@${VIRTUAL_HOST} | grep "Leaping Bunny"
echo "Testing login page..."
curl -sL -I http://${SHIELD_USER}:${SHIELD_PASS}@${VIRTUAL_HOST}/user/login | grep "HTTP/1.1 200 OK"
