<?php
/**
 * @file
 * Code for the AbleOrganizer Sample Content feature.
 */

include_once 'ableorganizer_sample_content.features.inc';

/**
 * Implements hook_preprocess_html().
 */
function ableorganizer_sample_content_preprocess_html() {
  drupal_add_library('system', 'ui', TRUE);
  drupal_add_library('system', 'effects', TRUE);
  drupal_add_library('system', 'effects.fade', TRUE);
  drupal_add_library('system', 'ui.dialog', TRUE);
}

/**
 * Implements hook_preprocess_page().
 */
function ableorganizer_sample_content_preprocess_page($variables) {
  if ($variables['is_front']) {
    drupal_add_js(drupal_get_path('module', 'ableorganizer_sample_content') . '/js/ableorganizer_sample_content.js');
  }
}
